spring:
  application:
    name: configserver
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/pulkit-chauhan07/eazybytes-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
        #native:
         # search-locations: "classpath:/config"
encrypt:
  key: "m7HoSCSkeaDqTvGZInhY5Q=="

server:
  port: 8071